=== flowerfine/rtomde/rtomde-platform/rtomde-platform-mybatis/src/main/java/cn/sliew/rtomde/platform/mybatis/builder/xml/mybatis-application-1.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT application (properties?, typeAliases?, environments?, mappers?)>
<!ATTLIST application
name CDATA #REQUIRED
>

<!ELEMENT properties (property*)>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
type CDATA #REQUIRED
alias CDATA #IMPLIED
>

<!ELEMENT environments (environment+)>

<!ELEMENT environment (hikaricp+, lettuce+)>
<!ATTLIST environment
id CDATA #REQUIRED
>

<!ELEMENT hikaricp (driverClassName, jdbcUrl, username, password, profileSQL)>
<!ATTLIST hikaricp
id CDATA #REQUIRED
>

<!ELEMENT jdbcUrl (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT driverClassName (#PCDATA)>
<!ELEMENT profileSQL (#PCDATA)>

<!ELEMENT lettuce (redisURI|clusterRedisURI)>
<!ATTLIST lettuce
id CDATA #REQUIRED
>

<!ELEMENT redisURI (#PCDATA)>
<!ELEMENT clusterRedisURI (#PCDATA)>

<!ELEMENT mappers (mapper*)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper
url CDATA #REQUIRED
>

=== flowerfine/rtomde/rtomde-platform/rtomde-platform-mybatis/src/test/java/cn/sliew/rtomde/platform/mybatis/session/MinimalMapperConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE application
    PUBLIC "-//mybatis.org//DTD Config 4.0//EN"
        "mybatis-application-1.dtd">

<application name="minimal">

    <environments>
        <environment id="local">
            <hikaricp id="rtomde">
                <driverClassName>com.mysql.cj.jdbc.Driver</driverClassName>
                <jdbcUrl>jdbc:mysql://localhost:3306/rtomde</jdbcUrl>
                <username>root</username>
                <password>123</password>
                <profileSQL>true</profileSQL>
            </hikaricp>
            <lettuce id="11">
                <redisURI></redisURI>
            </lettuce>
        </environment>
        <environment id="dev">
            <hikaricp id="rtomde">
                <driverClassName>com.mysql.cj.jdbc.Driver</driverClassName>
                <jdbcUrl>jdbc:mysql://localhost:3306/rtomde</jdbcUrl>
                <username>root</username>
                <password>123</password>
                <profileSQL>true</profileSQL>
            </hikaricp>
            <lettuce id="11">
                <redisURI></redisURI>
            </lettuce>
        </environment>
    </environments>

    <mappers>
        <mapper url="file:/Users/wangqi/Documents/git_repository/rtomde/rtomde-jdbc/src/test/java/org/apache/ibatis/session/SysUserMapper.xml"/>
    </mappers>

</application>

=== flowerfine/rtomde/rtomde-service/rtomde-service-springmvc/src/main/resources/boss_board-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application
		PUBLIC "-//sliew.cn//DTD Application 1.0//EN"
		"http://sliew.cn/dtd/mybatis-application-1.dtd">
<application name="boss_board">

	<typeAliases>
		<typeAlias alias="HashMap" type="java.util.HashMap" />
		<typeAlias alias="LinkedHashMap" type="java.util.LinkedHashMap" />
		<typeAlias alias="ArrayList" type="java.util.ArrayList" />
		<typeAlias alias="LinkedList" type="java.util.LinkedList" />
	</typeAliases>

	<environments>
		<environment id="dev">
			<hikaricp id="data_service">
				<driverClassName>com.mysql.cj.jdbc.Driver</driverClassName>
				<jdbcUrl>jdbc:mysql://localhost:3331/data_service</jdbcUrl>
				<username>root</username>
				<password>123</password>
				<profileSQL>true</profileSQL>
			</hikaricp>
			<lettuce id="local">
				<redisURI>redis://123@localhost:6379/0?timeout=1s</redisURI>
			</lettuce>
		</environment>
	</environments>

	<mappers>
		<mapper url="file:/Users/wangqi/Documents/xinc/rtomde/rtomde-service/rtomde-service-springmvc/src/main/resources/mapper/boss_board/SysUserMapper.xml"/>
	</mappers>

</application>

=== flowerfine/rtomde/rtomde-platform/rtomde-platform-mybatis/src/test/java/cn/sliew/rtomde/platform/mybatis/builder/ApplicationConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE application
    PUBLIC "-//sliew.cn//DTD Application 1.0//EN"
    "http://sliew.cn/dtd/mybatis-application-1.dtd">

<application name="rtomde">
    <properties>
        <property name="prop1" value="bbbb"/>
    </properties>

    <typeAliases>
        <typeAlias alias="Integer" type="java.lang.Integer" />
        <typeAlias alias="Long" type="java.lang.Long" />
        <typeAlias alias="HashMap" type="java.util.HashMap" />
        <typeAlias alias="LinkedHashMap" type="java.util.LinkedHashMap" />
        <typeAlias alias="ArrayList" type="java.util.ArrayList" />
        <typeAlias alias="LinkedList" type="java.util.LinkedList" />
    </typeAliases>

    <environments>
        <environment id="dev">
            <hikaricp id="data_service">
                <jdbcUrl>jdbc:mysql://localhost:3306/data_center</jdbcUrl>
                <username>root</username>
                <password>123</password>
                <driverClassName>com.mysql.cj.jdbc.Driver</driverClassName>
                <profileSQL>true</profileSQL>
            </hikaricp>
            <lettuce id="dev">
                <redisURI>redis://123@localhost:6379/0?timeout=1s</redisURI>
            </lettuce>
        </environment>
    </environments>

</application>
