=== flowerfine/rtomde/rtomde-jdbc/src/main/java/org/apache/ibatis/builder/xml/mybatis-4-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT mapper (resultMap* | parameterMap* | sql* | select* )+>
<!ATTLIST mapper
namespace CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)?>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
resultMap CDATA #IMPLIED
scale CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
extends CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
>

<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
resultMap CDATA #IMPLIED
timeout CDATA #IMPLIED
databaseId CDATA #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include (property+)?>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
 name CDATA #REQUIRED
 value CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
id CDATA #REQUIRED
lang CDATA #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== flowerfine/rtomde/rtomde-springmvc/src/main/resources/mapper/SysUserMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 4.0//EN"
        "http://mybatis.org/dtd/mybatis-4-mapper.dtd">
<mapper namespace="users" application="rtomde">

    <parameterMap id="UserParamMap" type="cn.sliew.rtomde.UserParam">
        <parameter property="id" javaType="long"/>
    </parameterMap>

    <resultMap id="UserResultMap" type="cn.sliew.rtomde.UserDTO">
        <result column="id" property="id" javaType="long"/>
        <result column="username" property="username" javaType="string"/>
        <result column="password" property="password" javaType="string"/>
        <result column="nickname" property="nickname" javaType="string"/>
        <result column="email" property="email" javaType="string"/>
        <result column="phone" property="phone" javaType="string"/>
        <result column="deleted" property="deleted" javaType="integer"/>
        <result column="create_time" property="createTime" javaType="date"/>
        <result column="creator" property="creator" javaType="string"/>
        <result column="update_time" property="updateTime" javaType="date"/>
        <result column="updater" property="updater" javaType="string"/>
        <result column="comments" property="comments" javaType="string"/>
    </resultMap>

    <sql id="Base_Column_List">
        id, username, `password`, nickname, email, phone, deleted, create_time, creator,
        update_time, updater, comments
    </sql>

    <select id="selectByPrimaryKey" dataSourceId="rtomde" parameterMap="UserParamMap" resultMap="UserResultMap">
        select <include refid="Base_Column_List"/>
        from sys_user
        where id = #{id}
    </select>
</mapper>
