=== flowerfine/rtomde/rtomde-jdbc/src/main/java/org/apache/ibatis/builder/xml/mybatis-4-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT configuration (properties?, settings?, typeAliases?, typeHandlers?, objectFactory?, objectWrapperFactory?, reflectorFactory?, plugins?, environments?, mappers?)>
<!ATTLIST configuration
application CDATA #REQUIRED
>

<!ELEMENT properties (property*)>
<!ATTLIST properties
resource CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT settings (setting+)>

<!ELEMENT setting EMPTY>
<!ATTLIST setting
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
type CDATA #REQUIRED
alias CDATA #IMPLIED
>

<!ELEMENT typeHandlers (typeHandler*)>

<!ELEMENT typeHandler EMPTY>
<!ATTLIST typeHandler
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
handler CDATA #REQUIRED
>

<!ELEMENT objectFactory (property*)>
<!ATTLIST objectFactory
type CDATA #REQUIRED
>

<!ELEMENT objectWrapperFactory EMPTY>
<!ATTLIST objectWrapperFactory
type CDATA #REQUIRED
>

<!ELEMENT reflectorFactory EMPTY>
<!ATTLIST reflectorFactory
type CDATA #REQUIRED
>

<!ELEMENT plugins (plugin+)>

<!ELEMENT plugin (property*)>
<!ATTLIST plugin
interceptor CDATA #REQUIRED
>

<!ELEMENT environments (environment+)>
<!ATTLIST environments
default CDATA #REQUIRED
>

<!ELEMENT environment (dataSource+)>
<!ATTLIST environment
id CDATA #REQUIRED
>

<!ELEMENT dataSource (property*)>
<!ATTLIST dataSource
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT mappers (mapper*)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper
url CDATA #IMPLIED
>

=== flowerfine/rtomde/rtomde-jdbc/src/test/resources/mybatis-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration
		PUBLIC "-//mybatis.org//DTD Config 4.0//EN"
		"http://mybatis.org/dtd/mybatis-4-config.dtd">
<configuration application="data-service">

	<properties resource="" url="">

	</properties>

	<settings>
		<setting name="logImpl" value="SLF4J"/>
	</settings>

	<typeAliases>
		<typeAlias alias="Integer" type="java.lang.Integer" />
		<typeAlias alias="Long" type="java.lang.Long" />
		<typeAlias alias="HashMap" type="java.util.HashMap" />
		<typeAlias alias="LinkedHashMap" type="java.util.LinkedHashMap" />
		<typeAlias alias="ArrayList" type="java.util.ArrayList" />
		<typeAlias alias="LinkedList" type="java.util.LinkedList" />
	</typeAliases>

	<typeHandlers>
		<typeHandler handler="" javaType="" jdbcType=""/>
	</typeHandlers>

	<environments default="dev">
		<environment id="dev">
			<dataSource id="magician" type="HikaricpPool">
				<property name="jdbcUrl" value="jdbc:mysql://localhost:3306/magician"/>
			</dataSource>
			<dataSource id="boss_board" type="HikaricpPool">
				<property name="jdbcUrl" value="jdbc:mysql://localhost:3306/boss_board"/>
			</dataSource>
		</environment>
	</environments>

	<mappers>
		<mapper url="http://api.dev.xinc818.com/magician/LiveAnchorMapper.xml" />
	</mappers>

</configuration>

=== flowerfine/rtomde/rtomde-service/rtomde-service-dubbo/src/main/resources/mybatis-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration
		PUBLIC "-//mybatis.org//DTD Config 4.0//EN"
		"http://mybatis.org/dtd/mybatis-4-config.dtd">
<configuration application="rtomde">

	<typeAliases>
		<typeAlias alias="HashMap" type="java.util.HashMap" />
		<typeAlias alias="LinkedHashMap" type="java.util.LinkedHashMap" />
		<typeAlias alias="ArrayList" type="java.util.ArrayList" />
		<typeAlias alias="LinkedList" type="java.util.LinkedList" />
	</typeAliases>

	<environments default="local">
		<environment id="local">
			<dataSource id="rtomde" type="HIKARICP">
				<property name="driver" value="com.mysql.cj.jdbc.Driver"/>
				<property name="url" value="jdbc:mysql://localhost:3306/rtomde"/>
				<property name="username" value="root"/>
				<property name="password" value="123"/>
			</dataSource>
			<lettuce id="rtomode" type="standalone">
				<property name="host" value="localhost"/>
				<property name="port" value="6379"/>
				<property name="password" value="123"/>
				<property name="database" value="0"/>
				<property name="timeout" value="1000"/>
			</lettuce>
		</environment>
		<environment id="dev">
			<dataSource id="rtomde" type="HIKARICP">
				<property name="driver" value="com.mysql.cj.jdbc.Driver"/>
				<property name="url" value="jdbc:mysql://test-xc-dev.mysql.rds.aliyuncs.com:3331/data_service"/>
				<property name="username" value="test_xc_dev"/>
				<property name="password" value="x!c@_d#ev$xcD_SdeAvM"/>
			</dataSource>
			<lettuce id="rtomode" type="standalone">
				<property name="host" value="localhost"/>
				<property name="port" value="6379"/>
				<property name="password" value="123"/>
				<property name="database" value="0"/>
				<property name="timeout" value="1000"/>
			</lettuce>
		</environment>
	</environments>

	<mappers>
		<mapper url="file:/Users/wangqi/Documents/git_repository/rtomde/rtomde-service/rtomde-service-dubbo/src/main/resources/mapper/SysUserMapper.xml"/>
	</mappers>
</configuration>

=== flowerfine/rtomde/rtomde-jdbc/src/test/java/org/apache/ibatis/session/MinimalMapperConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration
    PUBLIC "-//mybatis.org//DTD Config 4.0//EN"
    "http://mybatis.org/dtd/mybatis-4-config.dtd">

<configuration application="minimal">

    <environments default="dev">
        <environment id="local">
            <dataSource id="rtomde" type="UNPOOLED">
                <property name="driver" value="com.mysql.cj.jdbc.Driver"/>
                <property name="url" value="jdbc:mysql://localhost:3306/rtomde"/>
                <property name="username" value="root"/>
                <property name="password" value="123"/>
            </dataSource>
        </environment>
        <environment id="dev">
            <dataSource id="rtomde" type="UNPOOLED">
                <property name="driver" value="com.mysql.cj.jdbc.Driver"/>
                <property name="url" value="jdbc:mysql://test-xc-dev.mysql.rds.aliyuncs.com:3331/data_service"/>
                <property name="username" value="test_xc_dev"/>
                <property name="password" value="x!c@_d#ev$xcD_SdeAvM"/>
            </dataSource>
        </environment>
    </environments>

    <mappers>
        <mapper url="file:/Users/wangqi/Documents/git_repository/rtomde/rtomde-jdbc/src/test/java/org/apache/ibatis/session/SysUserMapper.xml"/>
    </mappers>
</configuration>
